User can edit an entry - Tiffany Brown
tiffanydbrown/code-journal pull request #7
Opened 2023-11-22 04:10 UTC by tiffanydbrown

Message in Slack.

2023-11-22 04:51 UTC, shawnkost requested changes
Some changes here Tiffany!

2023-11-22 04:51 UTC, shawnkost commented on js/main.js
>    $ul.prepend(renderEntry('entries'));
Delete this. We only want to create an entry if `data.editing === null`

2023-11-22 04:51 UTC, shawnkost commented on js/main.js
> +    renderEntry('entries');
You need to append the result of `renderEntry` to your `ul`. Right now, you're creating an entry, but aren't actually adding it to the webpage

2023-11-22 04:51 UTC, shawnkost commented on js/main.js
> +    console.log(formValues.entryId);
Remove all `console.log`s

2023-11-22 04:51 UTC, shawnkost commented on js/main.js
> +    );
This isn't going to work. You need to interpolate your `data.editing.entryId` into the template literal

2023-11-22 04:51 UTC, shawnkost commented on js/main.js
> +      $updateEntry.innerText = 'New Entry';
I don't think this is the correct element? Your `div` with the `data-view="entry-form"` is getting selected by this. You want your `h2` that says "New entry" to be the one that gets targeted by this

2023-11-22 16:53 UTC, tiffanydbrown commented
https://github.com/tiffanydbrown/code-journal/assets/139157669/7ee4c9d7-7d40-4fdc-a691-58ff5c42ef32

2023-11-23 00:41 UTC, shawnkost requested changes
Few changes here Tiffany!

2023-11-23 00:41 UTC, shawnkost commented on index.html
> +      crossorigin="anonymous"></script>
Not needed. This was already included for you

2023-11-23 00:41 UTC, shawnkost commented on js/main.js
> +    console.log(existingLi);
Remove all `console.log`s!

2023-11-23 00:41 UTC, shawnkost commented on js/main.js
> +  console.log(entry);
Remove all `console.log`s!

2023-11-23 00:57 UTC, shawnkost approved these changes
👍🏻

2023-11-24 16:48 UTC, merged